### ISSUE TITLE
你好，我不知道我能否获取到收益

### ISSUE THREAD

**Issue by Jetereting** [AdColony/AdColony-Android-SDK-3#17]
![image](https://cloud.githubusercontent.com/assets/11585188/26025913/4b34e5c8-3824-11e7-9bdf-9c465b93f1ea.png)
像是这里，只要我的Impressions和CVVs达到一定的值我就会有收益了吗？
![image](https://cloud.githubusercontent.com/assets/11585188/26025934/8c3939b6-3824-11e7-8ef5-81fb006c46d0.png)

还有这里的状态会不会影响到我的收益或者提现?

**Comment by cmanibog-ac** [comment]
Not linking the app's market ID in our dashboard will not affect your earnings or the number of video campaigns available to play in your app.

Google Translate: 
在资讯主页中连结应用程式的市场编号并不会影响您的收益或播放影片广告活动的次数。

**Comment by Jetereting** [comment]
谢谢，你简直太贴心了，但是我在中国内陆播放出来的广告都是AdConlony的样片。

Google Translate:
Thank you, you are really intimate, but I am in mainland China to play out of the ads are all AdConlony sample.

**Comment by cmanibog-ac** [comment]
Since our test ads are playing, you can assume that your integration is working properly as our test ads play exactly like our live ads do without the view limitations. 

With that said, our live ad fill in China will be severely limited. Also note that our campaigns are dependent on your location so your users that are in areas where there are more campaigns available will see videos, with highest fill seen in the Big Four english speaking countries (AU, CA, UK, US). On the other side of this, it is definitely possible for times when there are few or no videos available. 

Translate:
由于我们的测试广告正在播放，您可以假设您的集成正常工作，因为我们的测试广告与我们的实时广告完全相同，而且没有观看限制。

这样说，我们在中国的现场广告将受到严重限制。另请注意，我们的广告系列取决于您的位置，因此在有更多广告系列的地区的用户可以看到在四大英语国家（澳大利亚，加利福尼亚州，英国，美国）看到的视频。在另一方面，绝对有可能在几乎没有或没有视频可用的时候。

**Comment by Jetereting** [comment]
Thank you! It helps me a lot.
