### ISSUE TITLE
Null Object Reference

### ISSUE THREAD

**Issue by winnerawan** [AdColony/AdColony-Android-SDK-3#24]
hi..
i follow the example, but i get

```java
java.lang.NullPointerException: 
Attempt to invoke virtual method 'boolean com.adcolony.sdk.AdColonyInterstitial.show()' 
on a null object reference
```

how to fix this issue ?

**Comment by brittmullen** [comment]
This means that your AdColonyInterstitial object reference is null when you try to call show(). I would suggest to make sure that the object we pass back in the onRequestFilled() callback is stored in the proper scope and that you are not releasing it or otherwise changing the reference to null before attempting to show the ad.

**Comment by winnerawan** [comment]
i dont get it, can you give me sample work code ?

**Comment by brittmullen** [comment]
If you are using the app/zone ids from the public sample, these will always display test ads. If you are using your own app/zone ids, you will need to disable test ads for your zone(s) on the AdColony clients dashboard: https://clients.adcolony.com
