### ISSUE TITLE
Full-screen ads onRequestNotFilled

### ISSUE THREAD

**Issue by 7280423** [AdColony/AdColony-Android-SDK-3#42]
Full-screen ads can be successful in demo, but in my app onRequestNotFilled, I can't find any useful information

**Comment by 7280423** [comment]
AdColony.configure api 
public static boolean configure(Activity activity, @NonNull String appId, @NonNull String... zoneIds) {
        return configure(activity, (AdColonyAppOptions)null, appId, zoneIds);
    }

This API needs to hold a activity. This design is very bad. Why not application context?

**Comment by brittmullen** [comment]
Hey there, in our upcoming 3.3.6 release we are actually already adding additional configure() signatures that allow passing of an Application Context instead - thanks for the feedback.

Regarding your first concern, I think we'd need some more information to look into this. If dropping your specific app/zone ids into the demo seems to be working, I'd initially walk through the project setup/basic implementation steps to see if there's anything missing in your app or anything of interest in the logs. Otherwise, if you wouldn't mind, our support staff would be happy to help dig further into your integration (support@adcolony.com).

**Comment by 7280423** [comment]
> Hey there, in our upcoming 3.3.6 release we are actually already adding additional configure() signatures that allow passing of an Application Context instead - thanks for the feedback.
> 
> Regarding your first concern, I think we'd need some more information to look into this. If dropping your specific app/zone ids into the demo seems to be working, I'd initially walk through the project setup/basic implementation steps to see if there's anything missing in your app or anything of interest in the logs. Otherwise, if you wouldn't mind, our support staff would be happy to help dig further into your integration ([support@adcolony.com](mailto:support@adcolony.com)).

Thank you for your reply. The problem is that activity is null or destroyed. Do I think more hints or exception? Easy to solve problems
