### ISSUE TITLE
Option 2: Manually

### ISSUE THREAD

**Issue by sahujaunpuri** [AdColony/AdColony-Android-SDK-3#43]
buildscript {
    repositories {
        google()
        jcenter()

    }
    dependencies {
        //classpath 'com.android.tools.build:gradle:3.1.4'
        compile fileTree(dir: 'libs', include: ['*.jar'])
        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
    }
}

allprojects {
    repositories {
        google()
        maven {
            url  "https://adcolony.bintray.com/AdColony"
        }
        jcenter()
    }
}

task clean(type: Delete) {
    delete rootProject.buildDir
}

Can someone tell me right or wrong?

![12](https://user-images.githubusercontent.com/22550065/47740374-ae79e380-dc9d-11e8-87e9-19234091a618.png)

**Comment by sahujaunpuri** [comment]
getting this prob

> Could not find method compile() for arguments [directory 'libs'] on object of type org.gradle.api.internal.artifacts.dsl.dependencies.DefaultDependencyHandler.

**Comment by akwkong** [comment]
Could you try changing your `compile fileTree(dir: 'libs', include: ['*.jar'])` line to `implementation fileTree(dir: 'libs', include: ['*.jar'])`?

The `compile` configuration was deprecated with the Android Gradle Plugin 3.0.0 and replaced with `implementation` and `api`:
https://developer.android.com/studio/build/dependencies#dependency_configurations

I missed updating the Option 2: Manually section to use `implementation` instead of `compile` when updating the Project Setup page the other day. It should be up to date now.

**Comment by sahujaunpuri** [comment]
If you are not convinced, you can give it an edit by app.
Because i am completely new Android Studio.

[build_gradle.txt](https://github.com/AdColony/AdColony-Android-SDK-3/files/2531399/build_gradle.txt)

**Comment by sahujaunpuri** [comment]
> Could you try changing your `compile fileTree(dir: 'libs', include: ['*.jar'])` line to `implementation fileTree(dir: 'libs', include: ['*.jar'])`?
> 
> The `compile` configuration was deprecated with the Android Gradle Plugin 3.0.0 and replaced with `implementation` and `api`:
> https://developer.android.com/studio/build/dependencies#dependency_configurations
> 
> I missed updating the **Option 2: Manually section to use `implementation` instead of `compile` when updating the Project Setup page the other day. It should be up to date now.**

If possible, post the option to manually select the selected projects. That new person will be very useful

**Comment by akwkong** [comment]
I just noticed that you are putting everything into one build.gradle. You should have one top-level [build.gradle](https://developer.android.com/studio/build/#top-level) and a module-level [build.gradle](https://developer.android.com/studio/build/#module-level) per module. The top-level build.gradle file should be similar to this:
https://github.com/AdColony/AdColony-Android-SDK-3/blob/master/Demos/InterstitialDemo/build.gradle

And the module-level build.gradle file in your app folder should be similar to this:
https://github.com/AdColony/AdColony-Android-SDK-3/blob/master/Demos/InterstitialDemo/app/build.gradle

You should also put the libs folder you circled in your screenshot into the app folder since the `implementation fileTree(dir: 'libs', include: ['*.jar'])` line should be in your module-level build.gradle file.

**Comment by sahujaunpuri** [comment]
> I just noticed that you are putting everything into one build.gradle. You should have one top-level [build.gradle](https://developer.android.com/studio/build/#top-level) and a module-level [build.gradle](https://developer.android.com/studio/build/#module-level) per module. The top-level build.gradle file should be similar to this:
> https://github.com/AdColony/AdColony-Android-SDK-3/blob/master/Demos/InterstitialDemo/build.gradle
> 
> And the module-level build.gradle file in your app folder should be similar to this:
> https://github.com/AdColony/AdColony-Android-SDK-3/blob/master/Demos/InterstitialDemo/app/build.gradle
> 
> You should also put the libs folder you circled in your screenshot into the app folder since the `implementation fileTree(dir: 'libs', include: ['*.jar'])` line should be in your module-level build.gradle file.

**Comment by sahujaunpuri** [comment]
mr akwkong 
I have to talk to you personally about how it will be possible.
shivendrakumarsahu@gmail.com
