### ISSUE TITLE
not getting live ads

### ISSUE THREAD

**Issue by sahujaunpuri** [AdColony/AdColony-Android-SDK-3#59]
Hello,
We can help you with your issue.  Can you tell us your AppID and ZoneID that you're using in your app?  Please send us your information to support@adcolony.com and we will assist you directly. Thanks.

_Originally posted by @pchinn in https://github.com/AdColony/AdColony-Android-SDK-3/issues/51#issuecomment-456590329_

So far, my app is not getting live ads, whereas I have mailed all the information to support@adcolony.com at many times. What should I do next ?

Should I remove adcolony ads from my app

**Comment by mwhite-ac** [comment]
I can see that your app is reciving test impressions, so this is most likely related to the size of your user population.  I look at your app and see 0 Daily Active Users (DAU) reported, as this is the case our system won't send live ads as you have no active users for your app.  You must get to about 100 DAU to let our system know that your app is fully live and start delivering live ads. 

Additionally, note that live fill availability is related to the location of your users.  So as your user group grows, you can reach out to our Support team at support@adcolony.com, and let them know where most of your users are located so that they can let you know more about the fill availability for those areas.
