### ISSUE TITLE
minSdkVersion changed to 14.0 from 9.0 in 3.0.7

### ISSUE THREAD

**Issue by mustii82** [AdColony/AdColony-Android-SDK-3#6]
minSdkVersion changed to 14.0 from 9.0 in 3.0.7 why that?

**Comment by jgonfer** [comment]
That's a good question. Is API 14 a minimum requeriment?

**Comment by mustii82** [comment]
yes and I don't understand why

**Comment by jgonfer** [comment]
I see, the Demo projects have that requeriment. Maybe the AdColony Android Team could explain us this upgrade 🤔

**Comment by mwhite-ac** [comment]
There hasn't been an actual update to our required API level, we have been on API 14 since version 2.3.4 for ad playback.

**Comment by jgonfer** [comment]
That's true @mwhite-ac, I've checked my project and I also require API 14 for Android SDK 3.x.x in my GameMaker Extension: https://marketplace.yoyogames.com/assets/4812/adcolony-sdk-extension

I didn't remember it, I was carried away by panic haha 

Thanks for the explanation and happy new year! 🎉

**Comment by mustii82** [comment]
I can use 3.0.6 without API Level 14

**Comment by adcbryce** [comment]
3.0.6 has a minSdkVersion of 9. The value was set to 9 so that integration with MoPub would work seamlessly when integrating with our AAR. It is our fault that 3.0.7 has a minSdkVersion of 14 and is a mistake, but our next AAR release will have a minSdkVersion of 9.

Our SDK will not play ads below API 14, but you will still be able to integrate our library into your app if your minSdkVersion is lower. You may override the minSdkVersion in your AndroidManifest.xml in the meantime. Sorry for the confusion. Let us know if you require anymore information.
